// <auto-generated />
using FBSApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FBSApp.Migrations
{
    [DbContext(typeof(FBS_DB_Context))]
    [Migration("20230730235458_updatedCountryIDsOnAddresses")]
    partial class updatedCountryIDsOnAddresses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FBSApp.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            City = "Manchester",
                            CountryId = 54L,
                            Street = "Sir Matt Busby Way"
                        },
                        new
                        {
                            Id = 2L,
                            City = "London",
                            CountryId = 54L,
                            Street = "High Road"
                        },
                        new
                        {
                            Id = 3L,
                            City = "London",
                            CountryId = 54L,
                            Street = "Queen Elizabeth Olympic Park"
                        },
                        new
                        {
                            Id = 4L,
                            City = "London",
                            CountryId = 54L,
                            Number = "75",
                            Street = "Drayton Park"
                        },
                        new
                        {
                            Id = 5L,
                            City = "Manchester",
                            CountryId = 54L,
                            Street = "Etihad Campus"
                        },
                        new
                        {
                            Id = 6L,
                            City = "Liverpool",
                            CountryId = 54L,
                            Street = "Merseyside"
                        },
                        new
                        {
                            Id = 7L,
                            City = "Newcastle",
                            CountryId = 54L,
                            Street = "Newcastle upon Tyne"
                        },
                        new
                        {
                            Id = 8L,
                            City = "Birmingham",
                            CountryId = 54L,
                            Street = "Trinity Road"
                        },
                        new
                        {
                            Id = 9L,
                            City = "London",
                            CountryId = 54L,
                            Street = "Fulham Road"
                        },
                        new
                        {
                            Id = 10L,
                            City = "Liverpool",
                            CountryId = 54L,
                            Street = "Goodison Road"
                        },
                        new
                        {
                            Id = 11L,
                            City = "Sheffield",
                            CountryId = 54L,
                            Street = "Granville Road"
                        },
                        new
                        {
                            Id = 12L,
                            City = "Brighton",
                            CountryId = 54L,
                            Street = "Village Way"
                        },
                        new
                        {
                            Id = 13L,
                            City = "Wolverhampton",
                            CountryId = 54L,
                            Street = "Waterloo Road"
                        },
                        new
                        {
                            Id = 14L,
                            City = "London",
                            CountryId = 54L,
                            Street = "Whitehorse Lane"
                        },
                        new
                        {
                            Id = 15L,
                            City = "London",
                            CountryId = 54L,
                            Street = "Stevenage Road"
                        },
                        new
                        {
                            Id = 16L,
                            City = "Burnley",
                            CountryId = 54L,
                            Street = "Harry Potts Way"
                        },
                        new
                        {
                            Id = 17L,
                            City = "Bournemouth",
                            CountryId = 54L,
                            Street = "Kings Park"
                        },
                        new
                        {
                            Id = 18L,
                            City = "Cardiff",
                            CountryId = 195L,
                            Street = "Sloper Road"
                        },
                        new
                        {
                            Id = 19L,
                            City = "Cardiff",
                            CountryId = 54L,
                            Street = "Britannia Road"
                        },
                        new
                        {
                            Id = 20L,
                            City = "Leicester",
                            CountryId = 54L,
                            Street = "Filbert Way"
                        },
                        new
                        {
                            Id = 21L,
                            City = "Watford",
                            CountryId = 54L,
                            Street = "Vicarage Road"
                        },
                        new
                        {
                            Id = 22L,
                            City = "Huddersfield",
                            CountryId = 54L,
                            Street = "Stadium Way"
                        },
                        new
                        {
                            Id = 23L,
                            City = "Norwich",
                            CountryId = 54L,
                            Street = "Carrow Road"
                        });
                });

            modelBuilder.Entity("FBSApp.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Flag")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Antigua & Deps"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Bosnia Herzegovina"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Burkina"
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Central African Rep"
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36L,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39L,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 40L,
                            Name = "DR Congo"
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 50L,
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = 51L,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 52L,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 53L,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54L,
                            Name = "England"
                        },
                        new
                        {
                            Id = 55L,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 56L,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 57L,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 58L,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 59L,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 60L,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 61L,
                            Name = "France"
                        },
                        new
                        {
                            Id = 62L,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 63L,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 64L,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 65L,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 66L,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 67L,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 68L,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 69L,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 70L,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 71L,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 72L,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 73L,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 74L,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 75L,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 76L,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 77L,
                            Name = "India"
                        },
                        new
                        {
                            Id = 78L,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 79L,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 80L,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 81L,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 82L,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 83L,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 84L,
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 85L,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 86L,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 87L,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 88L,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 89L,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 90L,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 91L,
                            Name = "Korea North"
                        },
                        new
                        {
                            Id = 92L,
                            Name = "Korea South"
                        },
                        new
                        {
                            Id = 93L,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 94L,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 95L,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 96L,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 97L,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 98L,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 99L,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 100L,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 101L,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 102L,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 103L,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 104L,
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 105L,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 106L,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 107L,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 108L,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 109L,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 110L,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 111L,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 112L,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 113L,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 114L,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 115L,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 116L,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 117L,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 118L,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 119L,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 120L,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 121L,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 122L,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 123L,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 124L,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 125L,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 126L,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 127L,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 128L,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 129L,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 130L,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 131L,
                            Name = "Northern Ireland"
                        },
                        new
                        {
                            Id = 132L,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 133L,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 134L,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 135L,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 136L,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 137L,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 138L,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 139L,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 140L,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 141L,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 142L,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 143L,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 144L,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 145L,
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 146L,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 147L,
                            Name = "St Kitts & Nevis"
                        },
                        new
                        {
                            Id = 148L,
                            Name = "St Lucia"
                        },
                        new
                        {
                            Id = 149L,
                            Name = "Saint Vincent & the Grenadines"
                        },
                        new
                        {
                            Id = 150L,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 151L,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 152L,
                            Name = "Sao Tome & Principe"
                        },
                        new
                        {
                            Id = 153L,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 154L,
                            Name = "Scotland"
                        },
                        new
                        {
                            Id = 155L,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 156L,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 157L,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 158L,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 159L,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 160L,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 161L,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 162L,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 163L,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 164L,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 165L,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 166L,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 167L,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 168L,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 169L,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 170L,
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 171L,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 172L,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 173L,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 174L,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 175L,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 176L,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 177L,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 178L,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 179L,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 180L,
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = 181L,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 182L,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 183L,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 184L,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 185L,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 186L,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 187L,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 188L,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 189L,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 190L,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 191L,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 192L,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 193L,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 194L,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 195L,
                            Name = "Wales"
                        },
                        new
                        {
                            Id = 196L,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 197L,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 198L,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("FBSApp.Models.Stadium", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Stadiums");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AddressId = 1L,
                            Name = "Old Traford"
                        },
                        new
                        {
                            Id = 2L,
                            AddressId = 2L,
                            Name = "Tottenham Hotspur Stadium"
                        },
                        new
                        {
                            Id = 3L,
                            AddressId = 3L,
                            Name = "Londond Stadium"
                        },
                        new
                        {
                            Id = 4L,
                            AddressId = 4L,
                            Name = "Emirates Stadium"
                        },
                        new
                        {
                            Id = 5L,
                            AddressId = 5L,
                            Name = "Etihad Stadium"
                        },
                        new
                        {
                            Id = 6L,
                            AddressId = 6L,
                            Name = "Anfield"
                        },
                        new
                        {
                            Id = 7L,
                            AddressId = 7L,
                            Name = "St. James' Park"
                        },
                        new
                        {
                            Id = 8L,
                            AddressId = 8L,
                            Name = "Villa Park"
                        },
                        new
                        {
                            Id = 9L,
                            AddressId = 9L,
                            Name = "Stamford Bridge"
                        },
                        new
                        {
                            Id = 10L,
                            AddressId = 10L,
                            Name = "Goodison Park"
                        },
                        new
                        {
                            Id = 11L,
                            AddressId = 11L,
                            Name = "Bramall Lane"
                        },
                        new
                        {
                            Id = 12L,
                            AddressId = 12L,
                            Name = "Falmer Stadium"
                        },
                        new
                        {
                            Id = 13L,
                            AddressId = 13L,
                            Name = "Molineux"
                        },
                        new
                        {
                            Id = 14L,
                            AddressId = 14L,
                            Name = "Selhurst Park"
                        },
                        new
                        {
                            Id = 15L,
                            AddressId = 15L,
                            Name = "Craven Cottage"
                        },
                        new
                        {
                            Id = 16L,
                            AddressId = 16L,
                            Name = "Turf Moor"
                        },
                        new
                        {
                            Id = 17L,
                            AddressId = 17L,
                            Name = "Dean Court"
                        },
                        new
                        {
                            Id = 18L,
                            AddressId = 18L,
                            Name = "Cardiff City Stadium"
                        },
                        new
                        {
                            Id = 19L,
                            AddressId = 19L,
                            Name = "St Mary's Stadium"
                        },
                        new
                        {
                            Id = 20L,
                            AddressId = 20L,
                            Name = "King Power Stadium"
                        },
                        new
                        {
                            Id = 21L,
                            AddressId = 21L,
                            Name = "Vicarage Road"
                        },
                        new
                        {
                            Id = 22L,
                            AddressId = 22L,
                            Name = "Kirklees Stadium"
                        },
                        new
                        {
                            Id = 23L,
                            AddressId = 23L,
                            Name = "Carrow Road"
                        });
                });

            modelBuilder.Entity("FBSApp.Models.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StadiumId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Manchester United",
                            StadiumId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Tottenham Hotspur",
                            StadiumId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "West Ham United",
                            StadiumId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Arsenal",
                            StadiumId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Manchester City",
                            StadiumId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Liverpool",
                            StadiumId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Newcastle United",
                            StadiumId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Aston Villa",
                            StadiumId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Chelsea",
                            StadiumId = 9L
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Everton",
                            StadiumId = 10L
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Sheffield United",
                            StadiumId = 11L
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Brighton & Hove Albion",
                            StadiumId = 12L
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Wolverhampton Wanderers",
                            StadiumId = 13L
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Crystal Palace",
                            StadiumId = 14L
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Fulham",
                            StadiumId = 15L
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Burnley",
                            StadiumId = 16L
                        },
                        new
                        {
                            Id = 17L,
                            Name = "AFC Bournemouth",
                            StadiumId = 17L
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Cardiff City",
                            StadiumId = 18L
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Southampton",
                            StadiumId = 19L
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Leicester",
                            StadiumId = 20L
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Watford",
                            StadiumId = 21L
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Huddersfield Town",
                            StadiumId = 22L
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Norwich City",
                            StadiumId = 23L
                        });
                });

            modelBuilder.Entity("FBSApp.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "admin@gmail.com",
                            Password = "292EC360C5465021CE4D00E9AE9817CE231194940CF6CE9FDBEC486E73D9D30E6808758A8B6FCDF5EB0FFAB191A584327A4889240B5E485B4FBA6CA97E4FCEFE",
                            Role = "ADMIN",
                            Salt = new byte[] { 49, 104, 76, 160, 188, 31, 175, 86, 209, 169, 173, 143, 19, 233, 200, 99, 247, 85, 121, 245, 100, 242, 89, 124, 135, 133, 6, 93, 20, 249, 229, 170, 2, 109, 34, 239, 18, 212, 125, 236, 209, 196, 97, 209, 63, 30, 79, 142, 241, 89, 184, 63, 177, 150, 138, 119, 206, 93, 133, 137, 49, 149, 22, 234 }
                        });
                });

            modelBuilder.Entity("FBSApp.Models.Address", b =>
                {
                    b.HasOne("FBSApp.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FBSApp.Models.Stadium", b =>
                {
                    b.HasOne("FBSApp.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("FBSApp.Models.Team", b =>
                {
                    b.HasOne("FBSApp.Models.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadium");
                });
#pragma warning restore 612, 618
        }
    }
}
