using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace FBSApp.Migrations
{
    /// <inheritdoc />
    public partial class addedCountries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Flag = table.Column<byte[]>(type: "varbinary(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Id", "Flag", "Name" },
                values: new object[,]
                {
                    { 1L, null, "Afghanistan" },
                    { 2L, null, "Albania" },
                    { 3L, null, "Algeria" },
                    { 4L, null, "Andorra" },
                    { 5L, null, "Angola" },
                    { 6L, null, "Antigua & Deps" },
                    { 7L, null, "Argentina" },
                    { 8L, null, "Armenia" },
                    { 9L, null, "Australia" },
                    { 10L, null, "Austria" },
                    { 11L, null, "Azerbaijan" },
                    { 12L, null, "Bahamas" },
                    { 13L, null, "Bahrain" },
                    { 14L, null, "Bangladesh" },
                    { 15L, null, "Barbados" },
                    { 16L, null, "Belarus" },
                    { 17L, null, "Belgium" },
                    { 18L, null, "Belize" },
                    { 19L, null, "Benin" },
                    { 20L, null, "Bhutan" },
                    { 21L, null, "Bolivia" },
                    { 22L, null, "Bosnia Herzegovina" },
                    { 23L, null, "Botswana" },
                    { 24L, null, "Brazil" },
                    { 25L, null, "Brunei" },
                    { 26L, null, "Bulgaria" },
                    { 27L, null, "Burkina" },
                    { 28L, null, "Burundi" },
                    { 29L, null, "Cambodia" },
                    { 30L, null, "Cameroon" },
                    { 31L, null, "Canada" },
                    { 32L, null, "Cape Verde" },
                    { 33L, null, "Central African Rep" },
                    { 34L, null, "Chad" },
                    { 35L, null, "Chile" },
                    { 36L, null, "China" },
                    { 37L, null, "Colombia" },
                    { 38L, null, "Comoros" },
                    { 39L, null, "Congo" },
                    { 40L, null, "DR Congo" },
                    { 41L, null, "Costa Rica" },
                    { 42L, null, "Croatia" },
                    { 43L, null, "Cuba" },
                    { 44L, null, "Cyprus" },
                    { 45L, null, "Czech Republic" },
                    { 46L, null, "Denmark" },
                    { 47L, null, "Djibouti" },
                    { 48L, null, "Dominica" },
                    { 49L, null, "Dominican Republic" },
                    { 50L, null, "East Timor" },
                    { 51L, null, "Ecuador" },
                    { 52L, null, "Egypt" },
                    { 53L, null, "El Salvador" },
                    { 54L, null, "Equatorial Guinea" },
                    { 55L, null, "Eritrea" },
                    { 56L, null, "Estonia" },
                    { 57L, null, "Ethiopia" },
                    { 58L, null, "Fiji" },
                    { 59L, null, "Finland" },
                    { 60L, null, "France" },
                    { 61L, null, "Gabon" },
                    { 62L, null, "Gambia" },
                    { 63L, null, "Georgia" },
                    { 64L, null, "Germany" },
                    { 65L, null, "Ghana" },
                    { 66L, null, "Greece" },
                    { 67L, null, "Grenada" },
                    { 68L, null, "Guatemala" },
                    { 69L, null, "Guinea" },
                    { 70L, null, "Guinea-Bissau" },
                    { 71L, null, "Guyana" },
                    { 72L, null, "Haiti" },
                    { 73L, null, "Honduras" },
                    { 74L, null, "Hungary" },
                    { 75L, null, "Iceland" },
                    { 76L, null, "India" },
                    { 77L, null, "Indonesia" },
                    { 78L, null, "Iran" },
                    { 79L, null, "Iraq" },
                    { 80L, null, "Ireland" },
                    { 81L, null, "Israel" },
                    { 82L, null, "Italy" },
                    { 83L, null, "Ivory Coast" },
                    { 84L, null, "Jamaica" },
                    { 85L, null, "Japan" },
                    { 86L, null, "Jordan" },
                    { 87L, null, "Kazakhstan" },
                    { 88L, null, "Kenya" },
                    { 89L, null, "Kiribati" },
                    { 90L, null, "Korea North" },
                    { 91L, null, "Korea South" },
                    { 92L, null, "Kosovo" },
                    { 93L, null, "Kuwait" },
                    { 94L, null, "Kyrgyzstan" },
                    { 95L, null, "Laos" },
                    { 96L, null, "Latvia" },
                    { 97L, null, "Lebanon" },
                    { 98L, null, "Lesotho" },
                    { 99L, null, "Liberia" },
                    { 100L, null, "Libya" },
                    { 101L, null, "Liechtenstein" },
                    { 102L, null, "Lithuania" },
                    { 103L, null, "Luxembourg" },
                    { 104L, null, "Macedonia" },
                    { 105L, null, "Madagascar" },
                    { 106L, null, "Malawi" },
                    { 107L, null, "Malaysia" },
                    { 108L, null, "Maldives" },
                    { 109L, null, "Mali" },
                    { 110L, null, "Malta" },
                    { 111L, null, "Marshall Islands" },
                    { 112L, null, "Mauritania" },
                    { 113L, null, "Mauritius" },
                    { 114L, null, "Mexico" },
                    { 115L, null, "Micronesia" },
                    { 116L, null, "Moldova" },
                    { 117L, null, "Monaco" },
                    { 118L, null, "Mongolia" },
                    { 119L, null, "Montenegro" },
                    { 120L, null, "Morocco" },
                    { 121L, null, "Mozambique" },
                    { 122L, null, "Myanmar" },
                    { 123L, null, "Namibia" },
                    { 124L, null, "Nauru" },
                    { 125L, null, "Nepal" },
                    { 126L, null, "Netherlands" },
                    { 127L, null, "New Zealand" },
                    { 128L, null, "Nicaragua" },
                    { 129L, null, "Niger" },
                    { 130L, null, "Nigeria" },
                    { 131L, null, "Norway" },
                    { 132L, null, "Oman" },
                    { 133L, null, "Pakistan" },
                    { 134L, null, "Palau" },
                    { 135L, null, "Panama" },
                    { 136L, null, "Papua New Guinea" },
                    { 137L, null, "Paraguay" },
                    { 138L, null, "Peru" },
                    { 139L, null, "Philippines" },
                    { 140L, null, "Poland" },
                    { 141L, null, "Portugal" },
                    { 142L, null, "Qatar" },
                    { 143L, null, "Romania" },
                    { 144L, null, "Russian Federation" },
                    { 145L, null, "Rwanda" },
                    { 146L, null, "St Kitts & Nevis" },
                    { 147L, null, "St Lucia" },
                    { 148L, null, "Saint Vincent & the Grenadines" },
                    { 149L, null, "Samoa" },
                    { 150L, null, "San Marino" },
                    { 151L, null, "Sao Tome & Principe" },
                    { 152L, null, "Saudi Arabia" },
                    { 153L, null, "Senegal" },
                    { 154L, null, "Serbia" },
                    { 155L, null, "Seychelles" },
                    { 156L, null, "Sierra Leone" },
                    { 157L, null, "Singapore" },
                    { 158L, null, "Slovakia" },
                    { 159L, null, "Slovenia" },
                    { 160L, null, "Solomon Islands" },
                    { 161L, null, "Somalia" },
                    { 162L, null, "South Africa" },
                    { 163L, null, "South Sudan" },
                    { 164L, null, "Spain" },
                    { 165L, null, "Sri Lanka" },
                    { 166L, null, "Sudan" },
                    { 167L, null, "Suriname" },
                    { 168L, null, "Swaziland" },
                    { 169L, null, "Sweden" },
                    { 170L, null, "Switzerland" },
                    { 171L, null, "Syria" },
                    { 172L, null, "Taiwan" },
                    { 173L, null, "Tajikistan" },
                    { 174L, null, "Tanzania" },
                    { 175L, null, "Thailand" },
                    { 176L, null, "Togo" },
                    { 177L, null, "Tonga" },
                    { 178L, null, "Trinidad & Tobago" },
                    { 179L, null, "Tunisia" },
                    { 180L, null, "Turkey" },
                    { 181L, null, "Turkmenistan" },
                    { 182L, null, "Tuvalu" },
                    { 183L, null, "Uganda" },
                    { 184L, null, "Ukraine" },
                    { 185L, null, "United Arab Emirates" },
                    { 186L, null, "United Kingdom" },
                    { 187L, null, "United States" },
                    { 188L, null, "Uruguay" },
                    { 189L, null, "Uzbekistan" },
                    { 190L, null, "Vanuatu" },
                    { 191L, null, "Vatican City" },
                    { 192L, null, "Venezuela" },
                    { 193L, null, "Vietnam" },
                    { 194L, null, "Yemen" },
                    { 195L, null, "Zambia" },
                    { 196L, null, "Zimbabwe" }
                });

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: 1L,
                columns: new[] { "Password", "Salt" },
                values: new object[] { "CE6D652E264FDB262A53C3B37092E55E8C9CAE3DDFDEA0CA32B332547F99211458169C97C36E45F6048A4105FF2EA4D6C3D438E5354E7978D1AEB4E016E08EF8", new byte[] { 79, 89, 22, 68, 184, 223, 159, 247, 90, 85, 142, 50, 156, 217, 154, 221, 139, 160, 210, 207, 171, 98, 63, 185, 20, 93, 224, 132, 253, 253, 238, 205, 134, 229, 55, 79, 148, 66, 194, 29, 140, 160, 88, 13, 245, 65, 132, 109, 12, 0, 100, 248, 129, 87, 27, 245, 234, 244, 218, 198, 56, 126, 162, 206 } });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Countries");

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: 1L,
                columns: new[] { "Password", "Salt" },
                values: new object[] { "79FC2AA5454A196D8FF394B439AD3C4AC00114821738C23BB05AA69C6F342EBE56A7ED3168C1379773B45DE1BD2B02F5FD1BCC534BD7DDE0BE1CE3C33B1AEECB", new byte[] { 23, 47, 146, 60, 175, 131, 112, 93, 166, 113, 50, 101, 203, 71, 151, 213, 169, 203, 245, 232, 128, 142, 170, 185, 78, 166, 75, 191, 107, 106, 214, 199, 128, 179, 12, 81, 115, 184, 177, 7, 128, 9, 62, 224, 129, 235, 149, 113, 29, 137, 124, 79, 145, 89, 167, 243, 42, 153, 56, 193, 39, 144, 245, 68 } });
        }
    }
}
