// <auto-generated />
using FBSApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FBSApp.Migrations
{
    [DbContext(typeof(FBS_DB_Context))]
    [Migration("20230730221848_removedKosovoAsCountry")]
    partial class removedKosovoAsCountry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FBSApp.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Flag")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Antigua & Deps"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Bosnia Herzegovina"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Burkina"
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Central African Rep"
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36L,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39L,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 40L,
                            Name = "DR Congo"
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 50L,
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = 51L,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 52L,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 53L,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54L,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 55L,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 56L,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57L,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 58L,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 59L,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 60L,
                            Name = "France"
                        },
                        new
                        {
                            Id = 61L,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 62L,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 63L,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 64L,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 65L,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 66L,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 67L,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 68L,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 69L,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 70L,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 71L,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 72L,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 73L,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 74L,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 75L,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 76L,
                            Name = "India"
                        },
                        new
                        {
                            Id = 77L,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 78L,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 79L,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 80L,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 81L,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 82L,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 83L,
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 84L,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 85L,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 86L,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 87L,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 88L,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 89L,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 90L,
                            Name = "Korea North"
                        },
                        new
                        {
                            Id = 91L,
                            Name = "Korea South"
                        },
                        new
                        {
                            Id = 92L,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 93L,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 94L,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 95L,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 96L,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 97L,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 98L,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 99L,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 100L,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 101L,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 102L,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 103L,
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 104L,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 105L,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 106L,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 107L,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 108L,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 109L,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 110L,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 111L,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 112L,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 113L,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 114L,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 115L,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 116L,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 117L,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 118L,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 119L,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 120L,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 121L,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 122L,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 123L,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 124L,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 125L,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 126L,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 127L,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 128L,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 129L,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 130L,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 131L,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 132L,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 133L,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 134L,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 135L,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 136L,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 137L,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 138L,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 139L,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 140L,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 141L,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 142L,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 143L,
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 144L,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 145L,
                            Name = "St Kitts & Nevis"
                        },
                        new
                        {
                            Id = 146L,
                            Name = "St Lucia"
                        },
                        new
                        {
                            Id = 147L,
                            Name = "Saint Vincent & the Grenadines"
                        },
                        new
                        {
                            Id = 148L,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 149L,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 150L,
                            Name = "Sao Tome & Principe"
                        },
                        new
                        {
                            Id = 151L,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 152L,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 153L,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 154L,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 155L,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 156L,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 157L,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 158L,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 159L,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 160L,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 161L,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 162L,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 163L,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 164L,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 165L,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 166L,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 167L,
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 168L,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 169L,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 170L,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 171L,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 172L,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 173L,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 174L,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 175L,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 176L,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 177L,
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = 178L,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 179L,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 180L,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 181L,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 182L,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 183L,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 184L,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 185L,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 186L,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 187L,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 188L,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 189L,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 190L,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 191L,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 192L,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 193L,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 194L,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 195L,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("FBSApp.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "admin@gmail.com",
                            Password = "91A841874A385D6B30583DC8C96A5AA05E17E048969A98F1835DCF5BCD4EB967D36DBA91AC8D3C5F29AB7A31B0347F3F65B6321274712EBA68EF12510B16539C",
                            Role = "ADMIN",
                            Salt = new byte[] { 7, 255, 15, 6, 179, 98, 63, 99, 114, 93, 129, 123, 110, 153, 178, 229, 29, 103, 230, 83, 240, 111, 31, 159, 105, 118, 159, 171, 103, 101, 244, 229, 156, 125, 182, 158, 196, 190, 86, 132, 157, 244, 82, 189, 247, 59, 3, 43, 241, 249, 206, 183, 4, 82, 164, 219, 20, 160, 133, 175, 61, 207, 226, 214 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
